// <auto-generated />
namespace AspNetIdentityTry1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class mm19 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mm19));
        
        string IMigrationMetadata.Id
        {
            get { return "201706161418065_mm19"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
